### ISSUE TITLE
SSL has expired on the website

### ISSUE THREAD

**Issue by YUKI2eN3e** [iDevoid/risu-peanuts#4]
Apparently the SSL certificate was expired for the website.
If I try to go to the website it just returns a Cloudflare Error 526 Invalid SSL certificate.

**Comment by iDevoid** [comment]
Hi, thanks for letting me know..
I didn't aware of this since I am taking a lot of my time for developing my own app for business..
Please feel free to open any issue related to the sites, I'll definitely check that out!

I've also checked all the sites for HololiveID memeber, 3 of the sites seems to work fine for now. here are the screenshoots below:
![image](https://user-images.githubusercontent.com/47969743/99696267-18ea6000-2ac1-11eb-9a83-5fa8ec719845.png)
![image](https://user-images.githubusercontent.com/47969743/99696326-2bfd3000-2ac1-11eb-8886-6c142aec1c3f.png)
![image](https://user-images.githubusercontent.com/47969743/99696346-30c1e400-2ac1-11eb-8aa1-885d5bf696db.png)

once again, thank you for rising the issue! :+1:  :1st_place_medal:
